/**
 * GENERATED by `npm run fixtures` — do not edit by hand.
 *
 * Each positive fixture is a real board state, taken from a real solve path,
 * at which that technique fires, with exactly what it deduced there frozen in.
 * Each negative fixture is a board at which the technique correctly finds
 * nothing — the guard against a technique that starts over-firing and quietly
 * makes puzzles unsolvable.
 */

import { type Difficulty, type Digit, type TechniqueId } from '../../game/types';

export interface TechniquePositiveFixture {
  technique: TechniqueId;
  boardString: string;
  placements: { cellIndex: number; digit: Digit }[];
  eliminations: { cellIndex: number; digit: Digit }[];
  explanation: string;
}

export interface TechniqueNegativeFixture {
  technique: TechniqueId;
  boardString: string;
}

export interface GoldenPuzzleFixture {
  difficulty: Difficulty;
  seed: string;
  givens: string;
  solution: string;
  clueCount: number;
}

export const TECHNIQUE_POSITIVE_FIXTURES: TechniquePositiveFixture[] = [
  {
    "technique": "nakedSingle",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [
      {
        "cellIndex": 75,
        "digit": 4
      }
    ],
    "eliminations": [],
    "explanation": "4 is the only candidate left in r9c4."
  },
  {
    "technique": "hiddenSingleBox",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [
      {
        "cellIndex": 15,
        "digit": 5
      }
    ],
    "eliminations": [],
    "explanation": "r2c7 is the only cell in box 3 that can hold 5."
  },
  {
    "technique": "hiddenSingleLine",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [
      {
        "cellIndex": 15,
        "digit": 5
      }
    ],
    "eliminations": [],
    "explanation": "r2c7 is the only cell in row 2 that can hold 5."
  },
  {
    "technique": "pointingCandidates",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 59,
        "digit": 7
      },
      {
        "cellIndex": 77,
        "digit": 7
      }
    ],
    "explanation": "In box 2, 7 can only go in column 6 (r1c6, r2c6), so it can be removed from the rest of that column."
  },
  {
    "technique": "claimingCandidates",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 36,
        "digit": 7
      }
    ],
    "explanation": "In row 6, 7 can only go inside box 4 (r6c1, r6c3), so it can be removed from the rest of that box."
  },
  {
    "technique": "nakedPair",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 66,
        "digit": 4
      },
      {
        "cellIndex": 67,
        "digit": 4
      }
    ],
    "explanation": "r8c2, r8c8 in row 8 form a naked pair on 2/4, so those digits can be removed from the rest of the row."
  },
  {
    "technique": "hiddenPair",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 66,
        "digit": 4
      },
      {
        "cellIndex": 67,
        "digit": 4
      }
    ],
    "explanation": "8/9 in row 8 can only go in r8c4, r8c5, a hidden pair, so every other candidate in those cells goes."
  },
  {
    "technique": "nakedTriple",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 66,
        "digit": 4
      },
      {
        "cellIndex": 66,
        "digit": 8
      }
    ],
    "explanation": "r8c2, r8c5, r8c8 in row 8 form a naked triple on 2/4/8, so those digits can be removed from the rest of the row."
  },
  {
    "technique": "hiddenTriple",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 16,
        "digit": 3
      },
      {
        "cellIndex": 16,
        "digit": 4
      },
      {
        "cellIndex": 43,
        "digit": 2
      },
      {
        "cellIndex": 34,
        "digit": 2
      },
      {
        "cellIndex": 34,
        "digit": 3
      }
    ],
    "explanation": "1/7/8 in column 8 can only go in r2c8, r5c8, r4c8, a hidden triple, so every other candidate in those cells goes."
  },
  {
    "technique": "nakedQuad",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 35,
        "digit": 2
      },
      {
        "cellIndex": 35,
        "digit": 3
      },
      {
        "cellIndex": 35,
        "digit": 8
      }
    ],
    "explanation": "r4c2, r4c5, r4c6, r4c8 in row 4 form a naked quad on 2/3/4/8, so those digits can be removed from the rest of the row."
  },
  {
    "technique": "hiddenQuad",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 57,
        "digit": 4
      },
      {
        "cellIndex": 57,
        "digit": 9
      },
      {
        "cellIndex": 58,
        "digit": 4
      },
      {
        "cellIndex": 59,
        "digit": 9
      }
    ],
    "explanation": "1/5/6/7 in box 8 can only go in r7c4, r7c5, r7c6, r9c6, a hidden quad, so every other candidate in those cells goes."
  },
  {
    "technique": "xWing",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 55,
        "digit": 7
      },
      {
        "cellIndex": 14,
        "digit": 7
      },
      {
        "cellIndex": 59,
        "digit": 7
      }
    ],
    "explanation": "X-Wing on 7: in rows 1/9 the digit is confined to columns 2/6 (r1c2, r1c6, r9c2, r9c6), so 7 goes from those columns elsewhere."
  },
  {
    "technique": "simpleColouring",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 61,
        "digit": 3
      },
      {
        "cellIndex": 62,
        "digit": 3
      }
    ],
    "explanation": "Colouring on 3: r7c8, r7c9 can see both colours of the chain, and one colour must be true."
  },
  {
    "technique": "xyWing",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 15,
        "digit": 3
      },
      {
        "cellIndex": 16,
        "digit": 3
      },
      {
        "cellIndex": 17,
        "digit": 3
      }
    ],
    "explanation": "XY-Wing: pivot r1c2 (1/7) with pincers r1c7 and r2c3 means one of them is 3, so 3 goes from any cell seeing both."
  },
  {
    "technique": "swordfish",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 55,
        "digit": 7
      },
      {
        "cellIndex": 59,
        "digit": 7
      },
      {
        "cellIndex": 47,
        "digit": 7
      },
      {
        "cellIndex": 56,
        "digit": 7
      }
    ],
    "explanation": "Swordfish on 7: in rows 1/2/9 the digit is confined to columns 2/3/6 (r1c2, r1c6, r2c3, r2c6, r9c2, r9c6), so 7 goes from those columns elsewhere."
  },
  {
    "technique": "xyzWing",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 35,
        "digit": 2
      }
    ],
    "explanation": "XYZ-Wing: pivot r4c8 (2/3/8) with pincers r4c6 and r6c9 forces 2 into one of the three, so 2 goes from any cell seeing all of them."
  },
  {
    "technique": "wWing",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 3,
        "digit": 3
      }
    ],
    "explanation": "W-Wing: r1c7 and r3c5 both hold 1/3, linked by the two 1s in column 2, so 3 goes from any cell seeing both."
  },
  {
    "technique": "jellyfish",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 55,
        "digit": 7
      },
      {
        "cellIndex": 59,
        "digit": 7
      },
      {
        "cellIndex": 56,
        "digit": 7
      },
      {
        "cellIndex": 36,
        "digit": 7
      },
      {
        "cellIndex": 54,
        "digit": 7
      }
    ],
    "explanation": "Jellyfish on 7: in rows 1/2/6/9 the digit is confined to columns 1/2/3/6 (r1c2, r1c6, r2c3, r2c6, r6c1, r6c3, r9c2, r9c6), so 7 goes from those columns elsewhere."
  },
  {
    "technique": "forcingChain",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "placements": [
      {
        "cellIndex": 1,
        "digit": 1
      }
    ],
    "eliminations": [],
    "explanation": "Forcing chain: assuming r1c2 is 7 breaks the grid, so it must be 1."
  },
  {
    "technique": "uniqueRectangle",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5....1..8..6.19837.58.942..31",
    "placements": [],
    "eliminations": [
      {
        "cellIndex": 55,
        "digit": 2
      },
      {
        "cellIndex": 55,
        "digit": 4
      }
    ],
    "explanation": "Unique Rectangle on 2/4: r7c8, r8c2, r8c8 and r7c2 would have two solutions if r7c2 held only that pair, so it must take one of its other candidates."
  },
  {
    "technique": "fullHouse",
    "boardString": "514.6..9.267.9.5..3.85.42671.57..9.6936...47..8.6...5....1..8..6.19837.58.942.631",
    "placements": [
      {
        "cellIndex": 19,
        "digit": 9
      }
    ],
    "eliminations": [],
    "explanation": "box 1 has only one empty cell, so r3c2 must be 9."
  }
];

export const TECHNIQUE_NEGATIVE_FIXTURES: TechniqueNegativeFixture[] = [
  {
    "technique": "fullHouse",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1"
  },
  {
    "technique": "uniqueRectangle",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1"
  },
  {
    "technique": "xyzWing",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5....1..8..6.19837.58.942..31"
  },
  {
    "technique": "nakedSingle",
    "boardString": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5....1..8..6.19837.58.942.631"
  },
  {
    "technique": "hiddenTriple",
    "boardString": "5.4.6..9.26..9.5....85.42671.57..9.6936...47..8.6...5....1..8..6.19837.58.942.631"
  },
  {
    "technique": "hiddenQuad",
    "boardString": "5.4.6..9.26..9.5....85.42671.57..9.6936...47..8.6...5....1..8..6.19837.58.942.631"
  },
  {
    "technique": "xWing",
    "boardString": "5.4.6..9.267.9.5..3.85.42671.57..9.6936...47..8.6...5....1..8..6.19837.58.942.631"
  },
  {
    "technique": "simpleColouring",
    "boardString": "514.6..9.267.9.5..3.85.42671.57..9.6936...47..8.6...5....1..8..6.19837.58.942.631"
  },
  {
    "technique": "jellyfish",
    "boardString": "514.6..9.267.9.5..3.85.42671.57..9.6936...47..8.6...5....1..8..6.19837.58.942.631"
  },
  {
    "technique": "pointingCandidates",
    "boardString": "514.6.39.267.9.5..3985142671.57..9.6936...47..8.6...5....1..8..6.19837.58.942.631"
  },
  {
    "technique": "xyWing",
    "boardString": "514.6.39.267.9.5..3985142671.57..9.6936...47..8.6...5....1..8..6.19837.58.942.631"
  },
  {
    "technique": "swordfish",
    "boardString": "514.6.39.267.9.5..3985142671.57..9.6936...47..8.6...5....1..8..6.19837.58.942.631"
  },
  {
    "technique": "nakedTriple",
    "boardString": "5142673982673985.43985142671.57..9.69368..47..8.6..15....1..8..6.19837.58.942.631"
  },
  {
    "technique": "wWing",
    "boardString": "5142673982673985143985142671.57.29.69368..47..8.6..15....1..8..6.19837.58.942.631"
  },
  {
    "technique": "nakedQuad",
    "boardString": "51426739826739851439851426714573298693685.47..8.6..15....1..8..6.19837.58.942.631"
  },
  {
    "technique": "nakedPair",
    "boardString": "514267398267398514398514267145732986936851472.8.6..15....1..8..6.19837.58.942.631"
  },
  {
    "technique": "claimingCandidates",
    "boardString": "5142673982673985143985142671457329869368514727826..1534..1..8.96.19837.58.942.631"
  },
  {
    "technique": "hiddenPair",
    "boardString": "5142673982673985143985142671457329869368514727826491534.317.8.96.19837.58.942.631"
  },
  {
    "technique": "forcingChain",
    "boardString": "51426739826739851439851426714573298693685147278264915345317.8296219837458.942.631"
  },
  {
    "technique": "hiddenSingleBox",
    "boardString": "514267398267398514398514267145732986936851472782649153453176829621983745879425631"
  },
  {
    "technique": "hiddenSingleLine",
    "boardString": "514267398267398514398514267145732986936851472782649153453176829621983745879425631"
  }
];

export const GOLDEN_PUZZLE_FIXTURES: GoldenPuzzleFixture[] = [
  {
    "difficulty": "easy",
    "seed": "fixture-easy-0#0",
    "givens": "5.4.6..9.26..9......85.42671.57..9...36...4...8.6...5.......8..6.1..37.58.9.2...1",
    "solution": "514267398267398514398514267145732986936851472782649153453176829621983745879425631",
    "clueCount": 33
  },
  {
    "difficulty": "medium",
    "seed": "fixture-medium-0#1",
    "givens": "...8.64...3...75.2.9..12...1.5..8.73..3....6.6......5...4........197....76......1",
    "solution": "512836497836497512497512836125648973943751268678329154254163789381974625769285341",
    "clueCount": 26
  },
  {
    "difficulty": "hard",
    "seed": "fixture-hard-0#3",
    "givens": "2..97...49.3.6.....64....7.8.2....4......8...3.9...8.5..............531.....927.8",
    "solution": "281973564973564281564281973812359647657428139349716825125837496798645312436192758",
    "clueCount": 25
  },
  {
    "difficulty": "expert",
    "seed": "fixture-expert-0#3",
    "givens": ".......1..97...6.42.8....9...672....12....4.....9.....4...7......51....68..4.69.5",
    "solution": "654397218397218654218654397546723189129865473783941562462579831935182746871436925",
    "clueCount": 25
  },
  {
    "difficulty": "extreme",
    "seed": "fixture-extreme-0#21",
    "givens": "..59...8.917.8..4.2.3..59.74..7..8...2....5.9.3.1...6.5...71....94.3...6.........",
    "solution": "645917283917283645283645917456729831821364579739158462562471398194832756378596124",
    "clueCount": 29
  },
  {
    "difficulty": "master",
    "seed": "fixture-master-0#1",
    "givens": ".1.2....8.7.9....5..8.1.2......9....6.7....4.48...61.9.3.14....7.....45....5....1",
    "solution": "315274968274968315968315274153492687697831542482756139539147826721689453846523791",
    "clueCount": 26
  }
];
