/**
 * Regenerates `src/__tests__/fixtures/techniqueFixtures.ts`.
 *
 * Fixtures are captured from real solve paths rather than hand-written: it
 * walks generated puzzles technique by technique and freezes the first board
 * state at which each technique fires, along with exactly what it deduced
 * there, plus a board at which it correctly stays silent.
 *
 * Run it after adding a technique or changing the ladder:
 *
 *     npm run fixtures
 *
 * Then read the diff. A changed fixture means a technique's behaviour moved —
 * that is the signal the tests exist to give, so confirm it was intended
 * before committing.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { boardToString, cloneBoard } from '../src/game/board';
import { boardForPuzzle, generatePuzzle } from '../src/game/generator';
import { applyTechniqueResult } from '../src/game/techniques/apply';
import { TECHNIQUE_LADDER } from '../src/game/techniques/registry';
import {
  DIFFICULTIES,
  type Board,
  type Difficulty,
  type TechniqueId,
} from '../src/game/types';

interface PositiveFixture {
  technique: TechniqueId;
  boardString: string;
  placements: { cellIndex: number; digit: number }[];
  eliminations: { cellIndex: number; digit: number }[];
  explanation: string;
}

interface GoldenPuzzle {
  difficulty: Difficulty;
  seed: string;
  givens: string;
  solution: string;
  clueCount: number;
}

const PUZZLES_PER_TIER = 4;
const MAX_STEPS_PER_PUZZLE = 300;

const positiveFixtures = new Map<TechniqueId, PositiveFixture>();
const negativeFixtures = new Map<TechniqueId, string>();
const goldenPuzzles: GoldenPuzzle[] = [];

function recordBoardState(boardString: string, board: Board): void {
  for (const technique of TECHNIQUE_LADDER) {
    const result = technique.apply(cloneBoard(board));

    if (result === null) {
      if (!negativeFixtures.has(technique.id)) {
        negativeFixtures.set(technique.id, boardString);
      }
      continue;
    }

    if (!positiveFixtures.has(technique.id)) {
      positiveFixtures.set(technique.id, {
        technique: technique.id,
        boardString,
        placements: result.placements.map((placement) => ({ ...placement })),
        eliminations: result.eliminations.map((elimination) => ({ ...elimination })),
        explanation: result.explanation,
      });
    }
  }
}

function digitsToPuzzleString(digits: Uint8Array): string {
  return [...digits].map((digit) => (digit === 0 ? '.' : `${digit}`)).join('');
}

for (const difficulty of DIFFICULTIES) {
  for (let puzzleIndex = 0; puzzleIndex < PUZZLES_PER_TIER; puzzleIndex += 1) {
    const seed = `fixture-${difficulty}-${puzzleIndex}`;
    process.stdout.write(`generating ${seed}\n`);
    const puzzle = generatePuzzle(seed, difficulty);

    if (puzzleIndex === 0) {
      goldenPuzzles.push({
        difficulty,
        seed: puzzle.seed,
        givens: digitsToPuzzleString(puzzle.givens),
        solution: [...puzzle.solution].join(''),
        clueCount: puzzle.clueCount,
      });
    }

    const board = boardForPuzzle(puzzle);
    for (let step = 0; step < MAX_STEPS_PER_PUZZLE; step += 1) {
      recordBoardState(boardToString(board), board);

      let anyTechniqueFired = false;
      for (const technique of TECHNIQUE_LADDER) {
        const result = technique.apply(board);
        if (result !== null) {
          applyTechniqueResult(board, result);
          anyTechniqueFired = true;
          break;
        }
      }
      if (!anyTechniqueFired) {
        break;
      }
    }
  }
}

const uncaptured = TECHNIQUE_LADDER.filter(
  (technique) => !positiveFixtures.has(technique.id),
);

process.stdout.write(
  `\ncaptured ${positiveFixtures.size}/${TECHNIQUE_LADDER.length} techniques\n`,
);
if (uncaptured.length > 0) {
  process.stdout.write(
    `no positive fixture for: ${uncaptured.map((technique) => technique.id).join(', ')}\n`,
  );
}

const fileContents = `/**
 * GENERATED by \`npm run fixtures\` — do not edit by hand.
 *
 * Each positive fixture is a real board state, taken from a real solve path,
 * at which that technique fires, with exactly what it deduced there frozen in.
 * Each negative fixture is a board at which the technique correctly finds
 * nothing — the guard against a technique that starts over-firing and quietly
 * makes puzzles unsolvable.
 */

import { type Difficulty, type TechniqueId } from '../../game/types';

export interface TechniquePositiveFixture {
  technique: TechniqueId;
  boardString: string;
  placements: { cellIndex: number; digit: number }[];
  eliminations: { cellIndex: number; digit: number }[];
  explanation: string;
}

export interface TechniqueNegativeFixture {
  technique: TechniqueId;
  boardString: string;
}

export interface GoldenPuzzleFixture {
  difficulty: Difficulty;
  seed: string;
  givens: string;
  solution: string;
  clueCount: number;
}

export const TECHNIQUE_POSITIVE_FIXTURES: TechniquePositiveFixture[] = ${JSON.stringify(
  [...positiveFixtures.values()],
  null,
  2,
)};

export const TECHNIQUE_NEGATIVE_FIXTURES: TechniqueNegativeFixture[] = ${JSON.stringify(
  [...negativeFixtures.entries()].map(([technique, boardString]) => ({
    technique,
    boardString,
  })),
  null,
  2,
)};

export const GOLDEN_PUZZLE_FIXTURES: GoldenPuzzleFixture[] = ${JSON.stringify(
  goldenPuzzles,
  null,
  2,
)};
`;

const outputPath = join(
  __dirname,
  '..',
  'src',
  '__tests__',
  'fixtures',
  'techniqueFixtures.ts',
);
writeFileSync(outputPath, fileContents);
process.stdout.write(`wrote ${outputPath}\n`);
